/* 
 * The purpose this class is to include special opperators to the formula generated by the formula creator class
 * and send the formula with the special operators to the MPS class
 */
public class SpecialOperator {

}
