/* 
 * The purpose this class is to include special opperators to the formula generated by the formula creator class
 * and send the formula with the special operators to the MPS class
 */
public class SpecialOperator {

    /*
     * The Special Operator method will recieve the modified formula form the LTLSubstitution class. This method
     * will call the MPS class and pass the recieved modified formula in order to get the various pieces of this
     * formula. Once we recieve the pices of the divided formula this method will iterate thorugh the formula and
     * will check if the divided formula meets any of the conditions for its operators to modify it. If the
     * formula does meet a condition of an operator, the operator method will be called and modify the formula and
     * save the formula with the operation perform as the formula this method is checking. Once the checks are
     * completed, the resutling(Final) formula will be passed back to the LTL Substituter method for further
     * checks.
     */
}
